export default [
  { text: 'cat', phonetics: ['c', 'a', 't'] },
  { text: 'dog', phonetics: ['d', 'o', 'g'] },
  { text: 'hen', phonetics: ['h', 'e', 'n'] },
  { text: 'pig', phonetics: ['p', 'i', 'g'] },
  { text: 'fox', phonetics: ['f', 'o', 'x'] },
  { text: 'cub', phonetics: ['c', 'u', 'b'] },
  { text: 'jam', phonetics: ['j', 'a', 'm'] },
  { text: 'vet', phonetics: ['v', 'e', 't'] },
  { text: 'zip', phonetics: ['z', 'i', 'p'] },
  { text: 'web', phonetics: ['w', 'e', 'b'] },
  { text: 'sun', phonetics: ['s', 'u', 'n'] },
  { text: 'kid', phonetics: ['k', 'i', 'd'] },
  { text: 'lap', phonetics: ['l', 'a', 'p'] },
  { text: 'rug', phonetics: ['r', 'u', 'g'] },
  { text: 'box', phonetics: ['b', 'o', 'x'] },
  { text: 'fig', phonetics: ['f', 'i', 'g'] },
  { text: 'yak', phonetics: ['y', 'a', 'k'] },
  { text: 'mud', phonetics: ['m', 'u', 'd'] },
  { text: 'pan', phonetics: ['p', 'a', 'n'] },
  { text: 'jet', phonetics: ['j', 'e', 't'] },
  { text: 'bud', phonetics: ['b', 'u', 'd'] },
  { text: 'zip', phonetics: ['z', 'i', 'p'] },
  { text: 'wig', phonetics: ['w', 'i', 'g'] },
  { text: 'van', phonetics: ['v', 'a', 'n'] },
  { text: 'six', phonetics: ['s', 'i', 'x'] }
]